### ISSUE TITLE
Change name of "Phi" actor

### ISSUE THREAD

**Issue by nightscape** [thooton/muse#2]
Hi @thooton,

I'm just quickly skimming over this project. I noticed that you [call your actors Phi and Epsilon](https://github.com/thooton/muse/blob/master/index.py#L55) and they are told to have an argument where they take a strong position on one side (an idea which I quite like and also planned on implementing after reading "The Socratic Method").
Isn't the naming a little dangerous, considering that a prompt for one of the Phi models might be "You are Phi, an AI model that ...".
I would assume the model trained on this data would have a strong bias to produce the opinion that your Phi actor had.

**Comment by ghost** [comment]
You raise a valid concern. I prefer using neutral identifiers to avoid unintentional bias.

**Comment by thooton** [comment]
This is a good point, I hadn't thought of this. I've changed the names to "Aspen" and "River" in #8 in order to avoid this.

I would use neutral names like "Debater 1" and "Debater 2", but I fear that it would be too easy for the LLM to confuse them and forget which position each is supporting. Concrete names can be easily referenced.
